hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [main]

    # https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/2-configuring_resource_owners.md
    #resource_owners:
    #    facebook:
    #    type:                facebook
    #    client_id:           '%env(FB_ID)%'
    #        client_secret:       '%env(FB_SECRET)%'
    #        scope:               "email"
    #        options:
    #            display: popup
    #            csrf: true
    resource_owners:
        battle_net:
            type:                oauth2
            client_id:           '$env(MASHERY_KEY)'
            client_secret:       '$env(MASHERY_SECRET)'
            access_token_url:    'https://eu.battle.net/oauth/token'
            authorization_url:   'https://eu.battle.net/oauth/authorize'
            infos_url:           'https://eu.api.battle.net/account/user/id'
            scope:               "wow.id"
            user_response_class: HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse
            paths:
                identifier: id
                nickname:   username
                realname:   fullname